language: ruby
rvm:
  - 2.4.0
install:
  - gem install rainbow -v '2.2.1'
  - bundle install
  - RAILS_ENV=test bundle exec rake --trace db:create test
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bin/test
  - codeclimate-test-reporter
