default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/dev_eighty

test:
  <<: *default
  database: db/test_eighty

production:
  <<: *default
  database: db/prod_eighty
